[package]
name = "y_crypto"
version = "0.1.0"
authors = ["fikgol <hit.cs.lijun@gmail.com>"]
edition = "2018"
workspace = ".."

[dependencies]
secp256k1 = {version = "0.13.0",features = ["rand"]}
rand = "0.6"
ed25519-dalek = "0.9.1"
sha2 = "0.8"



